#pragma once

#include "NativeGameplayTags.h"

namespace EquipmentTypeTags
{
    namespace Equipment
    {
        EQUIPMENTMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)

        EQUIPMENTMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Head)
        EQUIPMENTMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UpperBody)
        EQUIPMENTMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LowerBody)
        EQUIPMENTMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hand)
        EQUIPMENTMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foot)

        EQUIPMENTMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tool)
    }
}

using namespace EquipmentTypeTags;
