#pragma once

#include "NativeGameplayTags.h"

namespace InteractionSystem
{
    namespace Interaction
    {
        INTERACTIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)

        INTERACTIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Open)
        INTERACTIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pickup)
        INTERACTIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Talk)
        INTERACTIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move)

        INTERACTIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Woodcutting)
        INTERACTIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mining)
        INTERACTIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fishing)
    }
}

using namespace InteractionSystem;
