#pragma once

#include "NativeGameplayTags.h"

namespace SocketGameplayTags
{
    namespace Socket
    {
        namespace Character
        {
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)

            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Head)
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hair)
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Face)
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ear)
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Beard)
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UpperBody)
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LowerBody)
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hand)
            SOCKETMANAGER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foot)
        }
    }
}

using namespace SocketGameplayTags;
